name: Node CI

on: [push]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: npm install
      run: npm ci
    - name: npm run build
      run: npm run build
    - name: npm run lint
      run: npm run lint
      env:
        CI: true
